name: Issue Template Action
description: Ensure new issues use a template.
inputs:
    closed-issue-message:
        description: Comment to add to closed issues.
        required: true
    closed-issue-label:
        description: Label to add to closed issues.
runs:
    using: node14
    main: dist/index.js
